### ISSUE TITLE
plot curves

### ISSUE THREAD

**Issue by blazar2019** [thuyngch/Iris-Recognition-PyTorch#1]
First of all, thank you for sharing the code. When I was copying modern codes, I had a problem with how your Loss and Accuracy curves were drawn. Is it "python visualization. py"? However, runtime error reporting, look forward to your reply

**Comment by thuyngch** [comment]
You can see this file [plot_tfboard.py](plot_tfboard.py). And the command is:
`
python plot_tfboard.py --dir train_dir
`
